### ISSUE TITLE
react native 

### ISSUE THREAD

**Issue by alfeyo** [OlivierJM/chai-mobile-updates#2]
- [x] react native run android. Not working.
wow, nice to see the app and server in one place. Points on that

**Comment by OlivierJM** [comment]
check this out https://github.com/OlivierJM/chai-updates

It basically needs a server to connect to.

**Comment by OlivierJM** [comment]
Let me come back soon

**Comment by OlivierJM** [comment]
this is also based on expo more info here https://expo.io

you run by simply `npm start`
