### ISSUE TITLE
Images on Mobile

### ISSUE THREAD

**Issue by OlivierJM** [OlivierJM/chai-mobile-updates#7]
For the reasons I know the images are not showing on IOS, this is caused by some issues with the network it needs https and it didn't accept ngrok.

@ikayz @alfeyo if you can manage to run it, you can test it out for me and see if it works on android.

**Comment by alfeyo** [comment]
sorry got lost in wordpress this week expo is running now thanks having a look at it this afternoon

**Comment by OlivierJM** [comment]
This issue was resolved
